### ISSUE TITLE
moodle_exception: A required parameter (vars) was missing

### ISSUE THREAD

**Issue by jackson-catalyst** [jmvedrine/moodle-qtype_algebra#8]
Hi Jean-Michel,

We've come across the following error on one of our client sites:

moodle_exception: Uncaught exception 'moodle_exception' with message 'A required parameter (vars) was missing' in /var/www/site/lib/setuplib.php:498
in print_error called at /var/www/site/lib/moodlelib.php (566)
in required_param called at /var/www/site/question/type/algebra/ajax.php (30)

Looks like plugin setting **Method to display answer formula (qtype_algebra | formuladisplay)** if set to Default - **Using an iframe element** generates this error.

https://github.com/jmvedrine/moodle-qtype_algebra/blob/master/renderer.php#L39 seems redundant when _formuladisplay_ is set to _iframe_ as that JS is not used at all.

Initialising the AMD call only for when _formuladisplay_ is _dynamic_ should fix this.

Thanks
Jackson

**Comment by jmvedrine** [comment]
Hello Jackson,
Thanks a lot for reporting this.
Unfortunately even if I still read comments for this github repo, I am now very old and I stopped all Moodle programming work many years ago.
So even if I setup a local repo, add a commit to fix this issue I would not be able to test that it solve the problem as I don't have a Moodle install to test it, and pushing it to github (ort even more doing a new release in the Moodle plugin database) without any testing seems not right at all.
The best I can do is to indicate how I "think" it could be fixed:
Replace the call to js_call_amd with
` 
       if (get_config('qtype_algebra', 'formuladisplay') == 'iframe') {
            $this->page->requires->js_call_amd('qtype_algebra/display', 'init');
        }
`
But you need to understand that I have not looked at any Moodle code line for several years and my memory is no more what it used to be !

**Comment by jmvedrine** [comment]
Reading your comment, my and the renderer code I wonder if it should be `=='iframe'` or `=='dynamic'` I must admit I am confused.

**Comment by jackson-catalyst** [comment]
Thank you Jean for your quick reply.

It should be `=='dynamic'` 

```
if (get_config('qtype_algebra', 'formuladisplay') == 'dynamic') {
    $this->page->requires->js_call_amd('qtype_algebra/display', 'init');
}
```

We have tested this on UAT server and seems to be working as expected.

Thank you once again :)

**Comment by aspark21** [comment]
Fixed. Can be closed

**Comment by jmvedrine** [comment]
Closing
